import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import SmoothScrolling from "@/components/SmoothScrolling";
import SmoothScroll from "@/components/SmoothScrolling";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const Sora = localFont({
  src: "./fonts/Sora-Regular.ttf",
  variable: "--font-sora-regular",
  weight: "400",
});

export const metadata = {
  title: "Brandio",
  description: "Generated by Brandio",
};

export default function RootLayout({ children }) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={`${Sora.variable} antialiased`}>
        <Navbar />
        {children}
        {/* <SmoothScroll>{children}</SmoothScroll> */}
        {/* <SmoothScrolling>{children}</SmoothScrolling> */}
        {/* <div></div> */}
        <Footer />
      </body>
    </html>
  );
}
